# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Q_theta_cpp <- function(para_vec_ori, para_vec_0_ori, yi_vec, m_star_vec, x_i_vec, l_i_vec, confound_mat, x4_inter, x5_inter) {
    .Call(`_ZIBM_Q_theta_cpp`, para_vec_ori, para_vec_0_ori, yi_vec, m_star_vec, x_i_vec, l_i_vec, confound_mat, x4_inter, x5_inter)
}

Q_theta_cpp_nz <- function(para_vec_ori, para_vec_0_ori, yi_vec, m_star_vec, x_i_vec, l_i_vec, confound_mat, x4_inter, x5_inter) {
    .Call(`_ZIBM_Q_theta_cpp_nz`, para_vec_ori, para_vec_0_ori, yi_vec, m_star_vec, x_i_vec, l_i_vec, confound_mat, x4_inter, x5_inter)
}

Q_theta_cpp_nomix <- function(para_vec_ori, yi_vec, m_star_vec, x_i_vec, l_i_vec, confound_mat, x4_inter, x5_inter) {
    .Call(`_ZIBM_Q_theta_cpp_nomix`, para_vec_ori, yi_vec, m_star_vec, x_i_vec, l_i_vec, confound_mat, x4_inter, x5_inter)
}

Q_theta_cpp_nz_nomix <- function(para_vec_ori, yi_vec, m_star_vec, x_i_vec, l_i_vec, confound_mat, x4_inter, x5_inter) {
    .Call(`_ZIBM_Q_theta_cpp_nz_nomix`, para_vec_ori, yi_vec, m_star_vec, x_i_vec, l_i_vec, confound_mat, x4_inter, x5_inter)
}

